import type { Metadata } from 'next';
import App from './app';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body>
        <App children={children} />
      </body>
    </html>
  );
}
